# Example compose file for production deployment on Linux.
#
# Note: This file is meant to serve as a template. Please modify it
# according to your needs. Read more about Docker Compose:
#
# https://docs.docker.com/compose/compose-file/
#
#
x-deploy: &default-deploy
  restart_policy:
    condition: unless-stopped
    delay: 5s
    window: 120s
  update_config:
    order: start-first

version: '3.7'

services:
  # mock-service:
  #   image: "nginx:1.23.3-alpine"
  #   restart: always
  #   environment:
  #   - NGINX_PORT=8080
  #   ports:
  #   - 10086:8080
  
  keycloak-db:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: bn_keycloak
      POSTGRES_PASSWORD: bitnami_keycloak
    volumes:
      - 'keycloak_db_data:/bitnami/postgresql'
    networks:
      - firezone-network

  keycloak:
    image: bitnami/keycloak:20.0.5-debian-11-r9
    restart: "no"
    ports:
      - 9090:9090
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: lfadmin
      KEYCLOAK_ADMIN_PASSWORD: "123"
      KEYCLOAK_DATABASE_HOST: keycloak-db
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: bn_keycloak
      KEYCLOAK_DATABASE_PASSWORD: bitnami_keycloak
      POSTGRES_PASSWORD: bitnami_keycloak
      KEYCLOAK_HTTP_PORT: 9090
    depends_on:
      - keycloak-db
    networks:
      - firezone-network
  
  # openldap:
  #   image: bitnami/openldap:2.5.14-debian-11-r9
  #   ports:
  #     - '1389:1389'
  #     # - '1636:1636'
  #   environment:
  #     - LDAP_ADMIN_USERNAME=admin
  #     - LDAP_ADMIN_PASSWORD=adminpassword
  #     - LDAP_USERS=u1@lf.test,u2@lf.test
  #     - LDAP_PASSWORDS=p1,p2
  #   networks:
  #     - firezone-network
  #   volumes
  #     - 'openldap_data:/bitnami/openldap'
  
  openid:
    image: "dexidp/dex:v2.36.0-alpine"
    restart: "always"
    networks:
      - firezone-network
    ports:
    - 5556:5556
    environment:
    - DEX_OAUTH2_ALWAYS_SHOW_LOGIN_SCREEN=true
    volumes:
    - ${FZ_INSTALL_DIR:-.}/dex.conf:/etc/dex/config.docker.yaml
    - ${FZ_INSTALL_DIR:-.}/dex:/var/dex
    depends_on:
    - dex-db
    - keycloak
    # - openldap

  dex-db:
    image: postgres:15.2-alpine3.17
    restart: "always"
    volumes:
      - dex-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - firezone-network

  firezone:
    image: firezone/firezone:${VERSION:-latest}
    ports:
      - ${WIREGUARD_PORT:-51820}:${WIREGUARD_PORT:-51820}/udp
    env_file:
      # This should contain a list of env vars for configuring Firezone.
      # See https://www.firezone.dev/docs/reference/env-vars for more info.
      - ${FZ_INSTALL_DIR:-.}/.env
    volumes:
      # IMPORTANT: Persists WireGuard private key and other data. If
      # /var/firezone/private_key exists when Firezone starts, it is
      # used as the WireGuard private. Otherwise, one is generated.
      - ${FZ_INSTALL_DIR:-.}/firezone:/var/firezone
    cap_add:
      # Needed for WireGuard and firewall support.
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      # Needed for masquerading and NAT.
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    depends_on:
      - postgres
      # - openid
    ports:
    # admin portal
    - 13000:13000
    networks:
      firezone-network:
        # ipv4_address: 172.25.0.100
        # ipv6_address: 2001:3990:3990::99

    deploy:
      <<: *default-deploy

  postgres:
    image: postgres:15.2-alpine3.17
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-firezone}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?err}
    networks:
      - firezone-network
    deploy:
      <<: *default-deploy
      update_config:
        order: stop-first

# Postgres needs a named volume to prevent perms issues on non-linux platforms
volumes:
  postgres-data:
  dex-postgres-data:
  keycloak_db_data:

networks:
  firezone-network:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
        - subnet: 2001:3990:3990::/64
          gateway: 2001:3990:3990::1
          